# Generated by Django 4.1.1 on 2023-03-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim', models.CharField(max_length=10)),
                ('mesh_term', models.CharField(max_length=10)),
                ('identifier', models.CharField(max_length=8)),
                ('coordinates', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='mimtoprot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim', models.CharField(max_length=10)),
                ('uniprot_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim1', models.CharField(max_length=10)),
                ('omim2', models.CharField(max_length=10)),
                ('similarity', models.CharField(max_length=10)),
                ('lca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='omim_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('prefix', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='omim_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ppi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactor_a', models.CharField(max_length=10)),
                ('interactor_b', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='similarityscores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim1', models.CharField(max_length=10)),
                ('omim2', models.CharField(max_length=10)),
                ('similarity', models.CharField(max_length=10)),
                ('percentile', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='similarityscores',
            index=models.Index(fields=['omim1'], name='omim1_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityscores',
            index=models.Index(fields=['omim2'], name='omim2_sim_idx'),
        ),
        migrations.AddIndex(
            model_name='neighbourhood',
            index=models.Index(fields=['omim1'], name='omim1_neigh_idx'),
        ),
        migrations.AddIndex(
            model_name='neighbourhood',
            index=models.Index(fields=['omim2'], name='omim2_neigh_idx'),
        ),
    ]
